config/routes.rb
LifeBills::Application.routes.draw do

  get "bills/export", as: :export_bills
  get "url/:url" => 'url#index'
  resources :weixin_users

  resources :materials

  resources :bills do 
    collection do 
      post 'search'
    end
  end

	namespace :weixin_web do 
		post 'user/bind',   as: 'bind'
    get 'user/signup', as: 'signup'
    get 'user/signin', as: 'signin'
    patch 'bills' => 'bills#update', as: 'bills'
    resources :bills do 
      get 'get_items', on: :collection
    end
	end

  devise_for :users do
    root to: 'home#index',as: 'auth_root'
  end

  root to: 'home#index'

  scope '/settings' do
    resources :people
    resources :accounts

    resources :items
	end

  

end

app/models/weixin_user.rb
class WeixinUser
  include Mongoid::Document 
  include Mongoid::Timestamps
  field :name, type: String
  field :delete_flag, type: Mongoid::Boolean
  field :weixin_id, type: String 
  field :signature, type: String  
  field :request_options, type: Hash
  field :type_flag, type: String
  
  belongs_to :user 
  belongs_to :person

  embeds_many :next_actions
  

  def user_or_person
    type_flag == 'user' ? user : person
  end
  
  class << self
    def signature_from(weixin_id)
      wuser = WeixinUser.where(weixin_id: weixin_id).first
      if wuser 
        wuser.signature
      end
    end
    def try_content(attr)
      m = Material.where(delete_flag: false,rule: 0,key_word: attr).first
      if m 
        m.content
      else
        attr
      end
    end
  end

  after_create :sigin_up_and_bind

  def sigin_up_and_bind
    next_actions.delete_all  
    next_actions.create([{
                            key_word: 1,remark: '登录并绑定',
                            weixin_type: 'link', content: short_url("weixin_web/user/signin")
                          },{
                            key_word: 2,remark: '新注册并绑定',
                            weixin_type: 'link', content: short_url("weixin_web/user/signup")
                          }])
  end  

  def after_bind_for_action
    next_actions.delete_all
    next_actions.create([{
                            key_word: 21,remark: '查看账单',
                            weixin_type: 'link', content: short_url("weixin_web/bills")
                          },{
                            key_word: 22,remark: '添加账单',
                            weixin_type: 'link', content: short_url("weixin_web/bills/new")
                          }])
  end

  def short_url(action)
    Settings.base_url + '/url/' + ShortUrl.generate("#{Settings.base_url}/#{action}?#{valid_str}")
  end

  def valid_str
    "weixin_id=#{weixin_id}&signature=#{signature}"
  end

end

app/controllers/weixin_users_controller.rb
class WeixinUsersController < ApplicationController
  before_action :set_weixin_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource 
  # GET /weixin_users
  # GET /weixin_users.json
  def index
    @weixin_users = WeixinUser.all
  end

  # GET /weixin_users/1
  # GET /weixin_users/1.json
  def show
  end

  # GET /weixin_users/new
  def new
    @weixin_user = WeixinUser.new
  end

  # GET /weixin_users/1/edit
  def edit
  end

  # POST /weixin_users
  # POST /weixin_users.json
  def create
    @weixin_user = WeixinUser.new(weixin_user_params)

    respond_to do |format|
      if @weixin_user.save
        format.html { redirect_to @weixin_user, notice: 'Weixin user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weixin_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @weixin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weixin_users/1
  # PATCH/PUT /weixin_users/1.json
  def update
    respond_to do |format|
      if @weixin_user.update(weixin_user_params)
        format.html { redirect_to @weixin_user, notice: 'Weixin user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weixin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weixin_users/1
  # DELETE /weixin_users/1.json
  def destroy
    @weixin_user.destroy
    respond_to do |format|
      format.html { redirect_to weixin_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weixin_user
      @weixin_user = WeixinUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weixin_user_params
      params.require(:weixin_user).permit(:user_id, :name, :delete_flag)
    end
end

app/views/weixin_users/_form.html.slim
= simple_form_for(@weixin_user) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user
    = f.input :name
    = f.input :delete_flag

  .form-actions
    = f.button :submit

app/views/weixin_users/edit.html.slim
h1 Editing weixin_user

== render 'form'

= link_to 'Show', @weixin_user
'|
= link_to 'Back', weixin_users_path

app/views/weixin_users/index.html.slim
h1 Listing weixin_users

table
  tr
    th User
    th Name
    th Delete flag
    th
    th
    th

  - @weixin_users.each do |weixin_user|
    tr
      td = weixin_user.user
      td = weixin_user.name
      td = weixin_user.delete_flag
      td = link_to 'Show', weixin_user
      td = link_to 'Edit', edit_weixin_user_path(weixin_user)
      td = link_to 'Destroy', weixin_user, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Weixin user', new_weixin_user_path

app/views/weixin_users/new.html.slim
h1 New weixin_user

== render 'form'

= link_to 'Back', weixin_users_path

app/views/weixin_users/show.html.slim
p#notice = notice

p
  strong User:
  = @weixin_user.user
p
  strong Name:
  = @weixin_user.name
p
  strong Delete flag:
  = @weixin_user.delete_flag

= link_to 'Edit', edit_weixin_user_path(@weixin_user)
'|
= link_to 'Back', weixin_users_path