config/routes.rb
LifeBills::Application.routes.draw do

  get "bills/export", as: :export_bills
  get "url/:url" => 'url#index'
  resources :weixin_users

  resources :materials

  resources :bills do 
    collection do 
      post 'search'
    end
  end

	namespace :weixin_web do 
		post 'user/bind',   as: 'bind'
    get 'user/signup', as: 'signup'
    get 'user/signin', as: 'signin'
    patch 'bills' => 'bills#update', as: 'bills'
    resources :bills do 
      get 'get_items', on: :collection
    end
	end

  devise_for :users do
    root to: 'home#index',as: 'auth_root'
  end

  root to: 'home#index'

  scope '/settings' do
    resources :people
    resources :accounts

    resources :items
	end

  

end

app/models/person.rb
class Person
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :password, type: String, default: '123456'
  field :order_id, type: Integer

  validates :name, presence: true
  validates :user_id, presence: true
  validates_with MasterValidator

  # embedded_in :user_info
  belongs_to :user
  has_many :weixin_user

  has_many :bills

  default_scope ->{ asc(:order_id) }
  
  def password_valid?(passwd)
    password == passwd
  end
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  load_and_authorize_resource except: [:create]
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = current_user.people.page(params[:page])
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = current_user.people.new(person_params)

    respond_to do |format|
      # return render json: @person if request.xhr?
      if @person.save
        format.html { redirect_to edit_person_path(@person), notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to edit_person_path(@person), notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :password, :order_id)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= simple_form_for @person,url: person_path(@person), html: {class: 'form-general form-horizontal'} do |f|
  - if @person.errors.any?
    #error_explanation
      h2 = "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      ul
        - @person.errors.full_messages.each do |message|
          li = message
  fieldset
    legend
      - if @person.new_record?
        = "添加成员"
      - else
        = "编辑成员"
  = f.input :name ,:label => '名称', label_html: {class: 'col-sm-2'}
  = f.input :order_id ,:label => '排序', label_html: {class: 'col-sm-2'}
  = f.input :password ,:label => '密码', label_html: {class: 'col-sm-2'}
  .actions
    .row
      .col-sm-2
      .col-sm-10
        = f.submit 'Save', class: 'btn btn-success'

app/views/people/edit.html.slim
== render 'form'

br
.row
  = link_to 'Show', @person, class: 'btn btn-info'
  | &nbsp&nbsp&nbsp&nbsp&nbsp
  = link_to 'Back', people_path , class: 'btn btn-info'

app/views/people/index.html.slim
h3 
  = 'Listing people'
  = link_to 'New Person', new_person_path, class: 'btn btn-info'

table.table.table-striped.table-hover.table-bordered
  tr
    th 序号
    th 名称    
    th 操作

  - @people.each_with_index do |person,index|
    tr id=person.to_param
      th = index + 1
      td = person.name
      td
        = link_to render_icon(:edit), edit_person_path(person)
        | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        = render_ajax_tr_remove_link(person)

.row
  = paginate @people
br

app/views/people/new.html.slim
== render 'form'

= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice = notice

p
  strong Name:
  = @person.name

= link_to 'Edit', edit_person_path(@person)
'|
= link_to 'Back', people_path