config/routes.rb
LifeBills::Application.routes.draw do

  get "bills/export", as: :export_bills
  get "url/:url" => 'url#index'
  resources :weixin_users

  resources :materials

  resources :bills do 
    collection do 
      post 'search'
    end
  end

	namespace :weixin_web do 
		post 'user/bind',   as: 'bind'
    get 'user/signup', as: 'signup'
    get 'user/signin', as: 'signin'
    patch 'bills' => 'bills#update', as: 'bills'
    resources :bills do 
      get 'get_items', on: :collection
    end
	end

  devise_for :users do
    root to: 'home#index',as: 'auth_root'
  end

  root to: 'home#index'

  scope '/settings' do
    resources :people
    resources :accounts

    resources :items
	end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController	  
  skip_before_action :authenticate_user!
  def index
    if user_signed_in?
      @bills = current_user.bills.bills_in_current_month      
    else
      render action: 'page'
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
h2
  =  render_home_h
table.table.table-striped.table-hover.table-bordered
  tr
    th 序号
    th 成员
    - for value in Settings.bill_types.values
      th = Settings.bill_types_zh[value]
  - current_user.people.each_with_index do |person,index|
    tr
      th
        = index + 1
      th
        = person.name
      - for value in Settings.bill_types.values
        th = @bills.person_of(person).type_of(value).sum(:money)
  - unless @bills.blank?
    tr
      th colspan=2 合计
      - for value in Settings.bill_types.values
        th = @bills.type_of(value).sum(:money)

app/views/home/page.html.slim
= simple_form_for(User.new, :as => :user, :url => session_path(:user),html: {class: 'form-sign-in form-horizontal'}) do |f|
  fieldset
    legend 登录
    = f.input :login, label:'登录名',label_html: {class: 'col-sm-2'}, placeholder: '邮件或帐号'
    = f.input :password, label: '密码',label_html: {class: 'col-sm-2'}, placeholder: '密码'

    - if devise_mapping.rememberable?
      .form-group
        .col-sm-2
        .col-sm-10
          = f.check_box :remember_me
          = f.label :remember_me
    .form-group.action
      .col-sm-2
      .col-sm-10
        = f.submit "登录", class:'btn btn-info'
    = render "devise/shared/links"