config/routes.rb
LifeBills::Application.routes.draw do

  get "bills/export", as: :export_bills
  get "url/:url" => 'url#index'
  resources :weixin_users

  resources :materials

  resources :bills do 
    collection do 
      post 'search'
    end
  end

	namespace :weixin_web do 
		post 'user/bind',   as: 'bind'
    get 'user/signup', as: 'signup'
    get 'user/signin', as: 'signin'
    patch 'bills' => 'bills#update', as: 'bills'
    resources :bills do 
      get 'get_items', on: :collection
    end
	end

  devise_for :users do
    root to: 'home#index',as: 'auth_root'
  end

  root to: 'home#index'

  scope '/settings' do
    resources :people
    resources :accounts

    resources :items
	end

  

end

app/models/account.rb
class Account
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String

  validates :name, presence: true
  validates :user_id, presence: true

  validates_with MasterValidator
  # embedded_in :user_info
  belongs_to :user

  has_many :bills

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource except: [:create]
  before_action :set_account, only: [:show, :edit, :update, :destroy]  
  # GET /accounts
  # GET /accounts.json 
  
  def index
    @accounts = current_user.accounts.page(params[:page])
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = current_user.accounts.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = current_user.accounts.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to edit_account_path(@account), notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to edit_account_path(@account), notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.slim
= simple_form_for @account,url: account_path(@account), html: {class: 'form-general form-horizontal'} do |f|
  - if @account.errors.any?
    #error_explanation
      h2 = "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      ul
        - @account.errors.full_messages.each do |message|
          li = message
  fieldset
    legend
      - if @account.new_record?
        = "添加账户"
      - else
        = "编辑账户"
  = f.input :name ,:label => '名称', label_html: {class: 'col-sm-2'}
  .actions
    .row
      .col-sm-2
      .col-sm-10
        = f.submit 'Save', class: 'btn btn-success'

app/views/accounts/edit.html.slim
== render 'form'

br
.row
  = link_to 'Show', @account, class: 'btn btn-info'
  | &nbsp&nbsp&nbsp&nbsp&nbsp
  = link_to 'Back', accounts_path , class: 'btn btn-info'

app/views/accounts/index.html.slim
h3 
  = 'Listing accounts'
  = link_to 'New Account', new_account_path, class: 'btn btn-info'

table.table.table-striped.table-hover.table-bordered
  tr
    th 序号
    th 名称
    th 操作
  - @accounts.each_with_index do |account,index|
    tr id=account.to_param
      th = index + 1
      td = account.name
      td
        = link_to render_icon(:edit), edit_account_path(account)
        | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        = render_ajax_tr_remove_link(account)

.row
  = paginate @accounts
br

app/views/accounts/new.html.slim
== render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
p#notice = notice

p
  strong Name:
  = @account.name

= link_to 'Edit', edit_account_path(@account)
'|
= link_to 'Back', accounts_path